definitions:
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.Document:
    properties:
      key:
        description: Logical key
        type: string
      meta:
        allOf:
        - $ref: '#/definitions/model.Metadata'
        description: Metadata for versioning, expiration, etc.
      value:
        description: 'Content: string, int, []string, map[string]any, etc.'
    type: object
  model.Metadata:
    properties:
      created_at:
        description: When document was created
        type: string
      expiration:
        description: TTL as Unix timestamp (0 = never)
        type: integer
      rev:
        description: Revision ID for conflict resolution
        type: string
      type:
        description: Document type (json, counter, list, set)
        type: string
      updated_at:
        description: When document was last updated
        type: string
    type: object
info:
  contact: {}
paths:
  /documents/insert:
    post:
      consumes:
      - application/json
      description: Insert a new document only if the key does not already exist
      parameters:
      - description: Document key
        in: query
        name: key
        required: true
        type: string
      - description: Column family (defaults to 'default')
        in: query
        name: cf
        type: string
      - description: Document type (json, counter, list, set)
        in: query
        name: type
        type: string
      - description: 'Write option: sync'
        in: query
        name: sync
        type: boolean
      - description: 'Write option: disable WAL'
        in: query
        name: disable_wal
        type: boolean
      - description: 'Write option: no slowdown'
        in: query
        name: no_slowdown
        type: boolean
      - description: Document value body. Must contain 'value' field
        in: body
        name: document
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Document'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Insert a document
      tags:
      - documents
swagger: "2.0"
